# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdb14604ca6852641338b69aa7dde7e1e1d50e77fbeeb69e53587686bc5437a3a34ce9f64475e0c8f2046a6c1fd2a4668e8387dc2b0bbb1593225696cbd2324e

test:
  secret_key_base: 5f6d488b3a8d60c95503f91941d97123b17e474ac99380e29a6722d5befafa51e1a239c6682dfc42fe327149a8730c51f6f68bfd7978f1b660664d2346989e2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
